"""followers

Revision ID: 720cabb7e450
Revises: 52c6cbc59dda
Create Date: 2022-10-04 17:41:15.536977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720cabb7e450'
down_revision = '52c6cbc59dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
